---
title: "Лабораторная работа по обработке данных"
author: "Притчин Иван"
date: '7 мая 2018 г '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=FALSE}
library(dplyr)
library(magrittr)
```

Исходным набором данных считать starwars
```{r}
head(starwars)
```

```{r}
data <- starwars

# Убрать из исходноuj массива последние три столца
data %<>% select(-(films:starships))
head(data)

# Выбрать имена столбцов с числовыми переменными
data %>% select_if(is.numeric) %>% head

# Вывести все столбцы, имена которых начинаются на "s"
data %>% select(starts_with("s")) %>% head

# Вывести все столбцы, имена которых содержат подстроку "color"
data %>% select(matches("color")) %>% head

# Вывести все столбцы, содержащие число 7
data %>% select_if(function(col) {
  79 %in% col
}) %>% head

# Вывести все столбцы, которые являются числовыми и среднее больше 90 (особое внимание значению NA)
data %>% select_if(function(col) {
  is.numeric(col) && mean(col, na.rm = TRUE) > 90
}) %>% head

# Вывести все столбцы кроме первого.
data %>% select(-1) %>% head

# Удалить последний два столбца
nColumn <- length(data)
data %>% select(-c(nColumn-1, nColumn)) %>% head
```


```{r}
starwars
```